name: marketplace
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.1.3
  shared_preferences: ^2.0.8
  file_picker: ^8.0.3
  cupertino_icons: ^1.0.6
  http: 1.2.1
  firebase_core: ^2.31.1
  cloud_firestore: ^4.17.4
  firebase_storage: ^11.7.6
  firebase_auth: ^4.19.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets:
    - img/apple.jpg
    - img/grapes.jpg
    - img/peach.jpg
    - img/strawberries.jpg
    - img/human.jpg
    - lib/data/
    - lib/userinfo/
